version: "3"
networks:
  mynetwork:
    ipam:
      config:
        - subnet: 172.20.0.0/24


services: 
    php_maline:
        build: ./
        restart: always
        volumes:     
            - .:/var/www/html/

        ports:
            - 8081:8081 
        command: php -S 172.20.0.3:8081    

        networks:
            mynetwork:
                ipv4_address: 172.20.0.3
               
  
            


  

   

             
    
               

  
    